# Задание 1.

Основные тезисы:

1) Под условие попадает примерно вся западная половина районов Москвы, некоторые города и поселки городского типа Московской Области;

2) Около 7.5 миллионов человек могут добраться до офиса Tele-2 за час с помощью общественного транспорта.

Данное задание, на мой взгляд, выполнено не идеально. Первоначально я хотел построить соответствующую изохрону, импортировав все требуемые данные - остановки метро, общественного транспорта и тд с помощью SQL и дальнейшей работы с ними. Однако после двух дней, затраченных на такое решение без особых результатов, я решил решить задание менее качественно, но более надежно, с помощью библиотек arcgis и geopy в Python.

In [1]:
# Приступим! Импортируем необходимую библиотеку для работы с геоданными.
from geopy import Nominatim as nm

# Загружаем библиотеки numpy и pandas для визуализации точек с помощью arcgis.
import numpy as np
import pandas as pd

# Импортируем библиотеку для визуализации результатов на карте Москвы.
import arcgis
from arcgis.gis import GIS

In [2]:
# Создаем объект geo соответствующего класса для работы с координатами и геолокацией.
geo = nm()

/anaconda3/lib/python3.6/site-packages/geopy/geocoders/osm.py:143: UserWarning: Using Nominatim with the default "geopy/1.17.0" `user_agent` is strongly discouraged, as it violates Nominatim's ToS https://operations.osmfoundation.org/policies/nominatim/ and may possibly cause 403 and 429 HTTP errors. Please specify a custom `user_agent` with `Nominatim(user_agent="my-application")` or by overriding the default `user_agent`: `geopy.geocoders.options.default_user_agent = "my-application"`. In geopy 2.0 this will become an exception.
  UserWarning


In [3]:
# Переменной location присваиваем адрес требуемого здания (офиса Теле-2).
location = geo.geocode("Москва, Киевское шоссе, 6/1")

In [4]:
# Проверим, правильное ли значение было присовено переменной.
location.address

'Киевское шоссе, поселение Московский, Новомосковский административный округ, Москва, ЦФО, 119027, РФ'

In [5]:
# Ошибка! Попробуем немного изменить форму записи.
location = geo.geocode("вл6 с1, 22 км Киевского шоссе, Москва")

In [6]:
# Вновь проверяем.
location.address

'Макет Comcity, вл6 с1 кА4, 22 км Киевского шоссе, поселение Московский, Новомосковский административный округ, Москва, ЦФО, 119606, РФ'

In [7]:
# То, что нужно! Выведем общую информацию о данном объекте.
location.raw

{'place_id': '52324366',
 'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright',
 'osm_type': 'node',
 'osm_id': '4119212089',
 'boundingbox': ['55.6351155', '55.6352155', '37.4313936', '37.4314936'],
 'lat': '55.6351655',
 'lon': '37.4314436',
 'display_name': 'Макет Comcity, вл6 с1 кА4, 22 км Киевского шоссе, поселение Московский, Новомосковский административный округ, Москва, ЦФО, 119606, РФ',
 'class': 'tourism',
 'type': 'attraction',
 'importance': 0.711,
 'icon': 'https://nominatim.openstreetmap.org/images/mapicons/poi_point_of_interest.p.20.png'}

Из этих данных нам существенны долгота, longitude, равная 37.4314436, и широта, latitude, которая, в свою очередь, равна 55.6351655.

Источники из интернета сообщают, что средняя скорость передвижения на общественном транспорте, будь то метро или наземный транспорт, составляет 41.5 км/ч с учетом остановок.

Путь до офиса состоит из дороги до общественного транспорта, непосредственной поездки на транспорте и дороги от остановки до офиса. Дорога до общественного транспорта плюс его ожидание (или спуск в метро) в среднем равна около 10 минутам. Путь от метро Румянцево или от троллейбусной/автобусной оставноки до офиса занимает по моему скромному опыту также порядка 10 минут. Соответственно, поездка на транспорте  должна занимать не более $60 - 10 - 10 = 40$ минут = $\frac{2}{3}$ часа. Со средней скоростью в 41.5 км/ч имеем $41.5 \cdot \frac{2}{3} \approx 27.6667$ километров.

Переведем данные единицы измерения в нужные нам: в одном градусе широты 111.134861111 километров. Разделив единицу на это число, получим количество градусов широты в 1 км. 1 / 111.134861111 = 0.00899807666. Аналогичным образом получим, что так как в одном градусе долготы 111.321377778 км, то в одном километре 0.008983000569 градусов. Таким образом, если разница между начальными и конечными координатами в $a$ градусов по долготе и $b$ градусов по широте, то расстояние в километрах равно $\sqrt{(\frac{a}{0.0089830})^2 + (\frac{b}{0.00899807})^2}$.

Итак, нас устраивают все районы, которые находятся на расстоянии 27.6667 километров. При переводе в градусы получим $\sqrt{(\frac{a}{0.0089830})^2 + (\frac{b}{0.00899807})^2} \leq 27.6667$. Возводя в квадрат обе части неравенства, получаем $(\frac{a}{0.0089830})^2 + (\frac{b}{0.00899807})^2 \leq 765.4445$. Теперь поделим стороны неравенства на 765.4445. $(\frac{a}{0.2485296})^2 + (\frac{b}{0.24894678})^2 \leq 1$. Данное уравнение характеризует элипс, включая всю его внутреннюю часть, с центром в исходной точке (координаты офиса Теле-2, как уже было выяснено, равны (37.4314436, 55.6351655) (долгота, широта)), у которого большая ось равна $2 \cdot 0.2485296 = 0.4970592$, а малая - $0.24894678 \cdot 2 = 0.49789356$. Нарисуем такое геометрическое место точек на карте.



In [8]:
# Для визуализации карты мы уже импортировали библиотеку arcgis. Заходим в аккаунт на сайте (логин и пароль указаны),
# создаем соответствующую переменную для работы.
gis = GIS(url='http://arcgis.com', username='Test_Akim', password='Testakim0')

In [9]:
# Посмотрим на Comcity с помощью данного модуля.
hello_map = gis.map("Москва, Comcity", zoomlevel = 16)

In [10]:
hello_map

MapView(layout=Layout(height='400px', width='100%'), zoom=16.0)

Отлично! Теперь требуется расставить крайние точки так, чтобы полученный ранее элипс охватывал все удовлетворяющие условию районы.

In [11]:
# Создаем список координат точек элипса по долготе. Соответствующие им координаты по широте выведем с помощью формулы элипса.
lon = np.arange(-0.2485296, 0.2485296, 10**(-2))

In [12]:
# Создадим два списка. В первый, lat_pos, поместим координаты точек элипса по широте, большие нуля. Соответственно,
# в другой список - меньшие нуля. 
lat_pos = [(1 - (i / 0.2485296)**2)**(1/2)*0.2485296 for i in lon]
lat_neg = [-i for i in lat_pos]

In [13]:
# Теперь инициализируем два списка: в первом лежат координаты точек, у которых изменение по широте "положительное",
# то есть к значению широты Comcity мы прибавляли какое-то значение. У координат точек из второго списка
# изменение по широте "отрицательное".
geom_pos = [(lon[i] + 37.4314436, lat_pos[i] + 55.6351655) for i in range(len(lon))]
geom_neg = [(lon[i] + 37.4314436, lat_neg[i] + 55.6351655) for i in range(len(lon))]

In [14]:
# Для каждого списка создадим DataFrame, который будет состоять из трех столбцов: долгота, широта и фактический адрес точки.
# Адрес будем получать с помощью геокода (geocode), зная координаты объекта. DataFrame нужна для визуализации данных точек на карте.
df_pos = {'Longitude': [j[0] for j in geom_pos], 'Latitude': [j[1] for j in geom_pos]}
df_pos = pd.DataFrame(df_pos)
df_pos['Address'] = [geo.geocode(
    '{0}, {1}'.format(df_pos.Latitude[i], df_pos.Longitude[i])).address for i in range(len(df_pos))]
df_pos

Longitude   Latitude                                            Address
0   37.182914  55.635165  Северный объезд Одинцова, сельское поселение Ж...
1   37.192914  55.704955  сельское поселение Горское, Одинцовский район,...
2   37.202914  55.732844  Государственная резиденция «Ново-Огарёво», Руб...
3   37.212914  55.753537  Александровка, городской округ Красногорск, Мо...
4   37.222914  55.770378  46К-9040, Ильинское-Усово, городской округ Кра...
5   37.232914  55.784675  46К-9030, Поздняково, городской округ Красного...
6   37.242914  55.797102  Изумрудные холмы, городской округ Красногорск,...
7   37.252914  55.808065  Гореносово, Изумрудные холмы, дачного хозяйств...
8   37.262914  55.817826  7, улица Огарёва, Гореносово, Опалиха, Красног...
9   37.272914  55.826569  Опалиховский лесопарк, Светлая улица, Опалиха,...
10  37.282914  55.834429  Госпиталь, Черневская улица, Столичный, Красно...
11  37.292914  55.841506  Черневская горка, улица Карбышева, Чернево, Кр...
12  37.302914  55.847879  проспект Краузе, Чернево, Росинка, городской о...
13  37.312914  55.853609  Брусчатый поселок, Росинка, городской округ Кр...
14  37.322914  55.858746  МФЖК «Ангелово-Резиденц», 46Н-04639, Митино, р...
15  37.332914  55.863330  46Н-04639, Митино, район Митино, городской окр...
16  37.342914  55.867393  Гаврилково, городской округ Красногорск, Моско...
17  37.352914  55.870962  Гаврилково, городской округ Красногорск, Моско...
18  37.362914  55.874060  ЭЖК «Эдем», Соколовская улица 1-й кв, Коттеджн...
19  37.372914  55.876705  с/т  Красногорочка, Гаврилково, городской окру...
20  37.382914  55.878911  Куркино, район Куркино, городской округ Красно...
21  37.392914  55.880690  17 к7, Куркинское шоссе, Куркино, район Куркин...
22  37.402914  55.882052  Куркинское шоссе, Куркино, район Куркино, Севе...
23  37.412914  55.883003  Химкинская Центральная городская больница, 11,...
24  37.422914  55.883549  8, Куркинское шоссе, Новобутаково, Химки, горо...
25  37.432914  55.883691  с2, Куркинское шоссе, Новобутаково, Химки, гор...
26  37.442914  55.883430  Ленинградское шоссе, район Левобережный, Север...
27  37.452914  55.882766  Химкинская больница, МКАД, 75-й километр, райо...
28  37.462914  55.881695  Центральный военно-клинический госпиталь №6, Л...
29  37.472914  55.880211  Химкинский лесопарк, МКАД, 77-й километр, райо...
30  37.482914  55.878307  Магнит, 44, улица Дыбенко, район Ховрино, Севе...
31  37.492914  55.875973  Северо-восточная хорда, район Ховрино, Северны...
32  37.502914  55.873197  Деповская улица, 11-й микрорайон Дегунино, Зап...
33  37.512914  55.869962  1, Талдомская улица, Западное Дегунино, район ...
34  37.522914  55.866250  улица Ивана Сусанина, Дегунино, район Западное...
35  37.532914  55.862037  Пяловская улица, Дегунино, район Западное Дегу...
36  37.542914  55.857295  Северо-восточная хорда, Головинский район, Сев...
37  37.552914  55.851988  Северо-Восточная хорда, Электродепо ТЧ-19 «Лих...
38  37.562914  55.846074  1 с9, 3-й Нижнелихоборский проезд, Нижние Лихо...
39  37.572914  55.839501  34 к1, Дмитровское шоссе, Нижние Лихоборы, Тим...
40  37.582914  55.832203  24Б, Малая Ботаническая улица, Марфино, район ...
41  37.592914  55.824095  Марфино, район Марфино, Северо-Восточный админ...
42  37.602914  55.815068  23А, улица Руставели, Бутырский, Бутырский рай...
43  37.612914  55.804976  16, Старомарьинское шоссе, Марьина Роща, район...
44  37.622914  55.793614  3, 4-я улица Марьиной Рощи, район Марьина Роща...
45  37.632914  55.780687  Городской туалет, Протопоповский переулок, Нап...
46  37.642914  55.765731  10, переулок Огородная Слобода, Ивановская гор...
47  37.652914  55.747939  15 с2, Николоямская улица, Швивая горка, Таган...
48  37.662914  55.725655  10, улица Симоновский Вал, Таганский район, Це...
49  37.672914  55.693979  Коломенка, район Нагатинский Затон, Южный адми...

In [15]:
# Аналогичная операция для точек с отрицательным изменением широты.
df_neg = {'Longitude': [j[0] for j in geom_neg], 'Latitude': [j[1] for j in geom_neg]}
df_neg = pd.DataFrame(df_neg)
df_neg['Address'] = [geo.geocode(
    '{0}, {1}'.format(df_neg.Latitude[i], df_neg.Longitude[i])).address for i in range(len(df_neg))]
df_neg

Longitude   Latitude                                            Address
0   37.182914  55.635165  Северный объезд Одинцова, сельское поселение Ж...
1   37.192914  55.565376  Киевское шоссе, поселение Марушкинское, Новомо...
2   37.202914  55.537487  улица Александра Печерского, поселение Первома...
3   37.212914  55.516794  46Н-06106, поселение Первомайское, Троицкий ад...
4   37.222914  55.499953  Ново-Спасское, поселение Первомайское, Троицки...
5   37.232914  55.485656  поселение Первомайское, Троицкий административ...
6   37.242914  55.473229  поселение Первомайское, Троицкий административ...
7   37.252914  55.462266  Малыгино, Троицкий административный округ, Мос...
8   37.262914  55.452505  поселение Краснопахорское, Троицкий администра...
9   37.272914  55.443762  Былово, Троицкий административный округ, Москв...
10  37.282914  55.435902  Калужское шоссе, поселение Краснопахорское, Тр...
11  37.292914  55.428825  Курорт Красная Пахра, 10 с1, Советская улица, ...
12  37.302914  55.422452  поселение Краснопахорское, Троицкий администра...
13  37.312914  55.416722  поселение Краснопахорское, Троицкий администра...
14  37.322914  55.411585  поселение Краснопахорское, Троицкий администра...
15  37.332914  55.407001  поселение Щаповское, Троицкий административный...
16  37.342914  55.402938  поселение Щаповское, Троицкий административный...
17  37.352914  55.399369  поселение Щаповское, Троицкий административный...
18  37.362914  55.396271  поселение Щаповское, Троицкий административный...
19  37.372914  55.393626  ЦКАД, поселение Щаповское, Троицкий администра...
20  37.382914  55.391420  поселение Щаповское, Троицкий административный...
21  37.392914  55.389641  Русино, Троицкий административный округ, Москв...
22  37.402914  55.388279  поселение Щаповское, Троицкий административный...
23  37.412914  55.387328  поселение Щаповское, Троицкий административный...
24  37.422914  55.386782  Стройрынок Молоток - 1, Варшавское шоссе, посе...
25  37.432914  55.386640  Хлыново, Троицкий административный округ, Моск...
26  37.442914  55.386901  Хлыново, Троицкий административный округ, Моск...
27  37.452914  55.387565  Костишово, Троицкий административный округ, Мо...
28  37.462914  55.388636  Костишово, Троицкий административный округ, Мо...
29  37.472914  55.390120  сельское поселение Лаговское, Бородино, городс...
30  37.482914  55.392024  сельское поселение Лаговское, Бородино, городс...
31  37.492914  55.394358  сельское поселение Лаговское, городской округ ...
32  37.502914  55.397134  Южный обход Подольска, сельское поселение Лаго...
33  37.512914  55.400369  сельское поселение Лаговское, Северово, городс...
34  37.522914  55.404081  СНТ Райисполком-2, сельское поселение Лаговско...
35  37.532914  55.408294  улица 40 летия Пионерии, Подольск, городской о...
36  37.542914  55.413036  Городская больница №3, улица Володи Дубинина, ...
37  37.552914  55.418343  ITPodolsk, 5, 1-й Деловой проезд, Зингер, Подо...
38  37.562914  55.424257  Подольск, городской округ Подольск, Московская...
39  37.572914  55.430830  Бронницкая улица, Подольск, городской округ По...
40  37.582914  55.438128  Домодедовское шоссе, сельское поселение Стрелк...
41  37.592914  55.446236  СНТ №1 ПЭЦЗ, Набережная улица, Подольск, город...
42  37.602914  55.455263  сельское поселение Стрелковское, Подольск, гор...
43  37.612914  55.465355  СНТ Быково, сельское поселение Стрелковское, П...
44  37.622914  55.476717  Центральная улица, сельское поселение Стрелков...
45  37.632914  55.489644  сельское поселение Стрелковское, Быковка, горо...
46  37.642914  55.504600  сельское поселение Стрелковское, Спирово, Лени...
47  37.652914  55.522392  Жилой комплекс  Суханово Парк, Булатниковское ...
48  37.662914  55.544676  Сосновый бор микрорайон, Расторгуево, городско...
49  37.672914  55.576352  8 к1, Ягодная улица, Бирюлёво, район Бирюлёво ...

In [16]:
# Загружаем каждую DataFrame в наш объект gis.
tick_1 = gis.content.import_data(df_pos, address_fields={"Address": "Address", "Longitude": "Longitude", "Latitude": "Latitude"})
tick_2 = gis.content.import_data(df_neg, address_fields={"Address": "Address", "Longitude": "Longitude", "Latitude": "Latitude"})

In [17]:
# Визуализируем! Настроим формат карты, размер, и добавим новые точки. Для того, чтобы увидеть на карте отмеченные точки,
# нужно нажать на иконку, на которой расположен монитор и земной шар возле "+" в левом верхнем углу карты.
new = gis.map('Москва', zoomlevel=9)
new.basemap = 'osm'
new.height = '600px'
new.add_layer(tick_1)
new.add_layer(tick_2)
new

MapView(basemap='osm', layout=Layout(height='400px', width='100%'), zoom=9.0)

Отлично! Худо-бедно у нас получилось визуализировать районы, из которых можно добратсья до офиса Tele-2 на общественном транспорте, затратив на поездку не более часа. Безусловно, данный метод был далек от идеального: он не учитывал, что, например, если человек живет возле красной ветки, пусть даже возле последних ее станций (Бульвар Рокоссовского и тд), он тоже сможет добраться до офиса за час, несмотря на большое расстояние; в свою очередь, жителю Подольска, который попал внутрь нашей изохроны, будет требоваться немного больше: яндекс навигатор, например, оценивает непосредственно время поездки, равное примерно часу. Соответственно, с учетом всех затрат житель Подольска сможет добраться до офиса примерно за час двадцать - час тридцать. Однако данная изохрона, имеющая форму элипса, и показывающая данную категорию людей вполне неплохо, позволяет оценить среднее количество населения, имеющих данную возможность. Изохрона делит площадь Москвы примерно пополам. Соответственно, так как население Москвы оценивается на 2018 год как 12 млн людей, 6 млн жителей Мосеквы имеет возможность добраться до офиса Tele-2 в течение часа посредством общественного транспорта. Общая численность населения городов и поселков городского типа Московской области, удовлетворяющих заданному условию, равна еще примерно полутора миллионам. Итоговая численность населения составляет 7.5 миллионов человек. Пересечение изобары с районами Москвы хорошо видно на карте: почти вся западная половина райнонов Москвы удовлетворяет условию.

In [18]:
gis.map('Queen Mary', )

MapView(layout=Layout(height='400px', width='100%'))